"""
E-MAIL HTML
"""


HTML_PASS_RECOVERY = (
    '<html xmlns="http://www.w3.org/1999/xhtml">'
        '<head>'
            '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />'
            '<title>Forgot Password</title>'
            '<style>'
                'body {{'
                    'background-color: #FFFFFF; padding: 0; margin: 0;'
                '}}'
            '</style>'
        '</head>'
        '<body>'
            '<table border="0" cellpadding="0" cellspacing="10" '
                'height="100%" bgcolor="#FFFFFF" width="100%" '
                'style="max-width: 650px;" id="bodyTable">'
                '<tr>'
                    '<td align="center" valign="top">'
                        '<table border="0" cellpadding="0" cellspacing="0" '
                            'width="100%" id="emailContainer" '
                            'style="font-family:Arial; color: #333333;">'
                            '<!-- Logo -->'
                            '<tr>'
                                '<td align="left" valign="top" colspan="2" '
                                    'style="border-bottom: 1px solid #CCCCCC; padding-bottom: '
                                    '10px;">'
                                    '<img alt="FIRELOC" border="0" src="https://fireloc.org/wp-content/uploads/2019/12/FireLOC-200.png" title="UNDERSEE" '
                                        'class="sitelogo" width="20%" style="max-width:100px;" />'
                                '</td>'
                            '</tr>'
                            '<!-- Title -->'
                            '<tr>'
                                '<td align="left" valign="top" colspan="2" style="border-bottom: 1px solid '
                                    '#CCCCCC; padding: 20px 0 10px 0;">'
                                    '<span style="font-size: 18px; font-weight: normal;">FORGOT PASSWORD</span>'
                                '</td>'
                            '</tr>'
                            '<!-- Messages -->'
                            '<tr>'
                                '<td align="left" valign="top" colspan="2" style="padding-top: 10px;">'
                                    '<span style="font-size: 12px; line-height: 1.5; color: #333333;">'
                                        'We have sent you this email in response to your request '
                                        'to reset your password on Fireloc web application.'
                                        '<br><br>'
                                        'To reset your password, please follow the link below:'
                                        '<a href="{url}{tk}">{url}{tk}</a>'
                                        '<br><br>'
                                        'We recommend that you keep your password secure and not share '
                                        'it with anyone.If you feel your password has been compromised, '
                                        'you can change it by going to your Undersee web application My Account Page '
                                        'and clicking on the "Change Email Address or Password" link.'
                                        '<br><br>'
                                        #'If you need help, or you have any other questions, feel free '
                                        #'to email {{customer-service-email}}, or call {{site-name}} customer '
                                        #'service toll-free at {{site-toll-free-number}}.'
                                        #'<br><br>'
                                        'Fireloc Team'
                                    '</span>'
                                '</td>'
                            '</tr>'
                        '</table>'
                    '</td>'
                '</tr>'
            '</table>'
        '</body>'
    '</html>'
)

HTML_USER_CONFIRMATION = (
    '<html xmlns="http://www.w3.org/1999/xhtml">'
        '<head>'
            '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />'
            '<title>Forgot Password</title>'
            '<style>'
                'body {{'
                    'background-color: #FFFFFF; padding: 0; margin: 0;'
                '}}'
            '</style>'
        '</head>'
        '<body>'
            '<table border="0" cellpadding="0" cellspacing="10" '
                'height="100%" bgcolor="#FFFFFF" width="100%" '
                'style="max-width: 650px;" id="bodyTable">'
                '<tr>'
                    '<td align="center" valign="top">'
                        '<table border="0" cellpadding="0" cellspacing="0" '
                            'width="100%" id="emailContainer" '
                            'style="font-family:Arial; color: #333333;">'
                            '<!-- Logo -->'
                            '<tr>'
                                '<td align="left" valign="top" colspan="2" '
                                    'style="border-bottom: 1px solid #CCCCCC; padding-bottom: '
                                    '10px;">'
                                    '<img alt="FIRELOC" border="0" src="https://fireloc.org/wp-content/uploads/2019/12/FireLOC-200.png" title="UNDERSEE" '
                                        'class="sitelogo" width="20%" style="max-width:100px;" />'
                                '</td>'
                            '</tr>'
                            '<!-- Title -->'
                            '<tr>'
                                '<td align="left" valign="top" colspan="2" style="border-bottom: 1px solid '
                                    '#CCCCCC; padding: 20px 0 10px 0;">'
                                    '<span style="font-size: 18px; font-weight: normal;">User Account activation</span>'
                                '</td>'
                            '</tr>'
                            '<!-- Messages -->'
                            '<tr>'
                                '<td align="left" valign="top" colspan="2" style="padding-top: 10px;">'
                                    '<span style="font-size: 12px; line-height: 1.5; color: #333333;">'
                                        'We have sent you this email to confirm your identity '
                                        'and to activate your Fireloc Account.'
                                        '<br><br>'
                                        'To activate your account, please follow the link below:'
                                        '<a href="{url}{tk}">{url}{tk}</a>'
                                        '<br><br>'
                                        'Fireloc Team'
                                    '</span>'
                                '</td>'
                            '</tr>'
                        '</table>'
                    '</td>'
                '</tr>'
            '</table>'
        '</body>'
    '</html>'
)